#!/usr/bin/env bash

set -e

tmpdir=$(mktemp -d)

cat <<EOF >> ${tmpdir}/kboom-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kboom
spec:
  template:
    spec:
      serviceAccountName: kboom-sa
      containers:
      - image: 661776721573.dkr.ecr.us-east-2.amazonaws.com/kboom:latest
        name: kboom
      restartPolicy: Never
EOF

kubectl apply -f ${tmpdir}/kboom-job.yaml